### PR TITLE
update values for dumpling

### PR DESCRIPTION
**Pull request by Danfro**
Dumpling allows limiting battery charge on my device, so updating the table accordingly

### CODE REVIEW

**Comment by Danfro** [comment]
And it gives me also time to full charge or remaing life time.

**Comment by paulcarroty** [comment]
> remaing life time

Kernel API or the upower output?

**Comment by Danfro** [comment]
I don't know. How can I find that out where the value comes from?

**Comment by paulcarroty** [comment]
In short - sysfs or upower output? Where you got it?

**Comment by Danfro** [comment]
Well, no idea how to query sysfs, but looking at the apps sourcecode for upower command, when I run that in terminal I get the "time to full" displayed there for my OP5T. On my suzu this value is missing.

Since my OP5T also shows the time to full on lockscreen, I think Muhammad did implement that, but the Xperia X doesn't show that, I assume upower is where the value comes from.

**Comment by paulcarroty** [comment]
It's calculated using energy rate (C-Rate): https://gitlab.freedesktop.org/upower/upower/-/blob/master/src/up-device-battery.c#L356

**Pull request merged**
